services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # host:container

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - frontend
