version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - '80:80'  # React apps usually run on 3000
