pipeline {
    agent any
    
    tools {
        nodejs "nodejs"
    }
    
     environment {
        NODE_ENV="PRODUCTION"

        DB_URI="mongodb+srv://donblezzy:Myschool12345@shopit.z1pjnwt.mongodb.net/ShopIT?retryWrites=true&w=majority&appName=ShopIT"
        
        JWT_SECRET = "S248ABCDEG1456"
        JWT_EXPIRES_TIME ="7d"
        COOKIE_EXPIRES_TIME="7"

        STRIPE_SECRET_KEY = "sk_test_51PIUrk05HB41KwPhsBA5XI3doaXHZJozb5x1jZTvXCxUGc0NQofuva0TBabp6bmSQhij3DwPzEiW6eUrCRx2bcUd001gqXyewX"
        STRIPE_WEBHOOK_SECRET = "whsec_2b7aec59c8b5571079f7d1fded23debb63948e1f101117a021790c402a84e6f6"

        SMTP_HOST ="sandbox.smtp.mailtrap.io"
        SMTP_PORT ="2525"
        SMTP_EMAIL ="7a25927854a3c8"
        SMTP_PASSWORD ="a25adde97748fc"
        SMTP_FROM_EMAIL ="noreply@shopit.com"
        SMTP_FROM_NAME ="ShopIT"

        CLOUDINARY_CLOUD_NAME = "df1zje8xy"
        CLOUDINARY_API_KEY = "343957393298166"
        CLOUDINARY_API_SECRET = "aXnEUwHah5Yni-sgJhLW9Dj3d5M"
    }


   
    stages {
        stage('Checkout Code') {
            steps {
                git branch: "jenkinsPractical", url:"https://github.com/donblezzy/e-commerce.git"  // Replace with your Git repo URL
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Install backend dependencies
                    sh 'npm install'

                    // Install frontend dependencies (if you have a separate frontend like React)
                    sh 'cd frontend && npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run backend tests (if any)
                    sh 'chmod +x ./jenkins/scripts/test.sh'

                    // Run frontend tests (if any)
                   // sh 'cd frontend && ./jenkins/scripts/test.sh'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Build frontend (for example, React build)
                    sh 'cd frontend && npm run build'

                    // Backend build steps (if any)
                    // For example, if you use Webpack, you can add the build step here.
                }
            }
        }

       

        
    }

    
}

